<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>StartupInspector.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TaskScheduler" Version="2.12.2" />
    <PackageReference Include="System.Diagnostics.EventLog" Version="10.0.12" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="10.0.12" />
  </ItemGroup>

</Project>
